"""
Decode text from single CDS
"""

from Procodon.decoder import Dnadecoder
from Procodon.utils import binary_to_text

#  Initialize Dnadecoder
dec = Dnadecoder(codec_path = 'Codec_112417.json')  #  Codec used here

#  Recoded sequence, can be replaced to other sequences
cds_seq = 'ATGGCCTCTACTGATTTTTCTAAAATTGAAACCTTGAAGCAGTTGAACGCTAGCTTAGCTGATAAGTCTTACATCGAAGGAACCGCCGTTTCCCAAGCAGATGTCACCGTTTTTAAAGCCTTTCAATCTGCTTACCCAGAGTTCTCTAGATGGTTCAACCACATCGCTTCCAAAGCCGACGAGTTCGATTCCTTCCCAGCCGCCTCTGCCGCAGCCGCCGAAGAAGAGGAGGATGACGACGTCGATCTATTCGGTTCCGACGACGAGGAGGCCGACGCTGAGGCCGAGAAGCTAAAGGCCGAGAGAATCGCAGCATACAATGCTAAAAAAGCCGCCAAGCCTGCAAAACCAGCCGCTAAATCCATCGTTACCTTGGATGTTAAGCCCTGGGACGATGAGACCAACTTGGAAGAAATGGTCGCAAATGTCAAGGCCATCGAAATGGAAGGCTTGACCTGGGGGGCCCATCAATTTATCCCAATTGGCTTCGGAATCAAAAAGTTGCAGATCAATTGTGTCGTCGAAGACGACAAGGTTTCTCTAGACGATCTACAGCAATCTATTGAGGAAGACGAAGACCACGTCCAATCAACTGATATTGCTGCTATGCAAAAATTATAA'
#  Decode binary string from CDS
dec_bin = dec.decode_cds(cds_seq)
#  Convert binary to text and print
print(binary_to_text(dec_bin))
