"""
Removal of intron from contigs by BLASTN result
"""
import sys
from Bio import SeqIO

def parse_intron_blastn(
    blastn_file: str, 
    intron_file: str, 
    contig_file: str, 
    out_cds_file: str
):
    """
    Remove intron from contigs

    Parameters:
        blastn_file: file path of BLASTN result generated by aligning introns with contigs, -outfmt 6
        intron_file: file path of intron sequences in FASTA format
        contig_file: file path of contig sequences in FASTA format
        out_cds_file: file path of output intron removed contig sequences in FASTA format
    """
    subj_dict = {}
    subj_seq_dict = {}
    del_pos_dict = {}
    cds_dict = {}
    intron_dict = {}
    
    #  Load intron length
    for record in SeqIO.parse(intron_file, 'fasta'):
        intron_dict[record.id] = len(record.seq)
    
    #  Load contig sequences and length
    for record in SeqIO.parse(contig_file, 'fasta'):
        subj_dict[record.id] = len(record.seq)
        subj_seq_dict[record.id] = str(record.seq)
        del_pos_dict[record.id] = {}
        #  Initialize dictionary containing intron positions with intron ID as keys
        for qname in intron_dict:
            del_pos_dict[record.id][qname] = []
    
    #  Parse BLASTN results
    with open(blastn_file, 'r') as f:
        for line in f:
            #  Get alignment information from each line
            qname = line.strip().split('\t')[0]
            sname = line.strip().split('\t')[1]
            q_start = int(line.strip().split('\t')[6]) - 1
            q_end = int(line.strip().split('\t')[7])
            s_start = int(line.strip().split('\t')[8])
            s_end = int(line.strip().split('\t')[9])
            
            if s_end > s_start:
                s_start -= 1
                strand = 1
            else:
                a = s_end - 1
                s_end = s_start
                s_start = a
                strand = -1
            #  Alignment long enough / intron at the end of contigs
            if (q_end - q_start) > (intron_dict[qname] * 0.85) or s_start <= 3 or s_end >= subj_dict[sname] - 3:
                if strand == 1:
                    act_s_start = max([0, s_start - q_start])
                    act_s_end = min([subj_dict[sname], s_end + (intron_dict[qname] - q_end)])
                else:
                    act_s_start = max([0, s_start - (intron_dict[qname] - q_end)])
                    act_s_end = min([subj_dict[sname], s_end + q_start])
                if del_pos_dict[sname][qname] == []:
                    del_pos_dict[sname][qname] = [act_s_start, act_s_end]
    
    for sname in del_pos_dict:
        #  Get regions for deletion
        del_list = [del_pos_dict[sname][qname] for qname in del_pos_dict[sname]]
        if del_list[0]:
            del_list = sorted(del_list, key = lambda x: x[0])
            pos_list = [0]
            for region in del_list:
                pos_list += region
            pos_list.append(subj_dict[sname])
            
            #  Determine regions to be kept
            cds_seq = ''
            for i in range(int(len(pos_list)/2)):
                cds_seq += subj_seq_dict[sname][pos_list[i * 2]: pos_list[i * 2 + 1]]
            cds_dict[sname] = cds_seq
        else:
            cds_dict[sname] = subj_seq_dict[sname]
    
    #  Intron removed contigs write into files
    with open(out_cds_file, 'w') as hd:
        for sname in cds_dict:
            if len(cds_dict[sname]) > 2:
                hd.write('>' + sname + '\n' + cds_dict[sname] + '\n')

if __name__ == '__main__':
    #  Get file path of BLASTN result, intron sequences, contig sequences and output intron removed contig sequences
    blastn_file = sys.argv[1]
    intron_file = sys.argv[2]
    contig_file = sys.argv[3]
    out_cds_file = sys.argv[4]

    #  Run main program
    parse_intron_blastn(blastn_file, intron_file, contig_file, out_cds_file)
