"""
Reads correction by AA
"""
import random
from Proteinstorage.utils import split_CDS
from Bio import SeqIO
from Bio.Seq import Seq
import sys

#  Codon table for most species
genetic_code = {
    'ATA': 'I', 'ATC': 'I', 'ATT': 'I', 'ATG': 'M',
    'ACA': 'T', 'ACC': 'T', 'ACG': 'T', 'ACT': 'T',
    'AAC': 'N', 'AAT': 'N', 'AAA': 'K', 'AAG': 'K',
    'AGC': 'S', 'AGT': 'S', 'AGA': 'R', 'AGG': 'R',
    'CTA': 'L', 'CTC': 'L', 'CTG': 'L', 'CTT': 'L',
    'CCA': 'P', 'CCC': 'P', 'CCG': 'P', 'CCT': 'P',
    'CAC': 'H', 'CAT': 'H', 'CAA': 'Q', 'CAG': 'Q',
    'CGA': 'R', 'CGC': 'R', 'CGG': 'R', 'CGT': 'R',
    'GTA': 'V', 'GTC': 'V', 'GTG': 'V', 'GTT': 'V',
    'GCA': 'A', 'GCC': 'A', 'GCG': 'A', 'GCT': 'A',
    'GAC': 'D', 'GAT': 'D', 'GAA': 'E', 'GAG': 'E',
    'GGA': 'G', 'GGC': 'G', 'GGG': 'G', 'GGT': 'G',
    'TCA': 'S', 'TCC': 'S', 'TCG': 'S', 'TCT': 'S',
    'TTC': 'F', 'TTT': 'F', 'TTA': 'L', 'TTG': 'L',
    'TAC': 'Y', 'TAT': 'Y', 'TAA': '*', 'TAG': '*',
    'TGC': 'C', 'TGT': 'C', 'TGA': '*', 'TGG': 'W'
}

def calculate_mutations(
    codon1: str, 
    codon2: str
):
    """
    Calculate mutations between 2 codons

    Parameters:
        codon1: query 3-bp codon in string
        codon2: subject 3-bp codon in string
    
    Return:
        Number of different bases of these two codons, int
    """
    codon1 = codon1.upper()
    codon2 = codon2.upper()

    return sum(1 for a, b in zip(codon1, codon2) if a != b)

def find_alternative_codons(
    input_codon: str, 
    target_aa: str
):
    """
    Finding codon from the correct amino acid with minimal mutations
    
    Parameters:
        input_codon: input codon sequence; e.g. "AAA"
        target_aa: 1-letter amino acid; e.g. "K"
    
    Return:
        tuple: (True: translatable / False: untranslatable, replacable codon list, minimal mutations)
    """
    # Check if the input codon can be translated into target aa
    if genetic_code.get(input_codon) == target_aa:
        return True, [input_codon], 0
    
    # Extract available codons
    valid_codons = [codon for codon, aa in genetic_code.items() if aa == target_aa]
    
    # Calculate mutations
    mutation_counts = {}
    for codon in valid_codons:
        mutations = calculate_mutations(input_codon, codon)
        if mutations not in mutation_counts:
            mutation_counts[mutations] = []
        mutation_counts[mutations].append(codon)
    
    # Finding the minimal mutations
    if not mutation_counts:
        return False, [], float('inf')
    
    min_mutations = min(mutation_counts.keys())
    alternative_codons = mutation_counts[min_mutations]
    
    return False, alternative_codons, min_mutations

def determine_codon_mutation(
    input_codon: str, 
    target_aa: str
):
    """
    Check and determine the codons for replacement
    
    Parameters:
        input_codon: input codon sequence; e.g. "AAA"
        target_aa: 1-letter amino acid; e.g. "K"
    
    Return:
        mut_dict: Codon indexes and bases for replacement
    """
    # Search alternative codons
    can_translate, alternatives, min_mutations = find_alternative_codons(input_codon, target_aa)
    
    if can_translate:
        return {}
    else:
        mut_dict = {}
        alt_codon = random.choice(alternatives)
        for i in range(3):
            if not input_codon[i] == alt_codon[i]:
                mut_dict[i] = alt_codon[i]
        return mut_dict

def extract_TBLASTN_line(
    blast_out_line: str
):
    """
    Extract TBLASTN regions

    Parameter:
        blast_out_line: line of TBLASTN result generated by -outfmt 6, str
    
    Return:
        tblastn_info: list containing reads ID, protein start, protein end, ORF start, ORF end, direction and identity
    """
    
    blast_data_list = blast_out_line.split('\t')
    
    reads_id = blast_data_list[1]
    prot_start = int(blast_data_list[6]) - 1
    prot_end = int(blast_data_list[7])
    orf_start = int(blast_data_list[8])
    orf_end = int(blast_data_list[9])
    identity = float(blast_data_list[-1])

    if orf_start > orf_end:
        c = orf_end - 1
        orf_end = orf_start
        orf_start = c
        direction = -1
    else:
        orf_start -= 1
        direction = 1
    
    #  Avoid frame shift
    if (orf_end - orf_start) / (prot_end - prot_start) == 3:
        tblastn_info = [reads_id, prot_start, prot_end, orf_start, orf_end, direction, identity]
        return tblastn_info
    else:
        return []

def extract_TBLASTN(
    blast_out_path: str
):
    """
    Parse TBLASTN result and store in dictionary with reads IDs as keys

    Parameter:
        blast_out_path: file path of TBLASTN result generated by -outfmt 6
    
    Return:
        tblastn_info_dict: dictionary containing TBLASTN information with reads IDs as keys
    """
    tblastn_info_dict = {}

    with open(blast_out_path, 'r') as f:
        lines = f.read().splitlines()
    
    for line in lines:
        #  Extract TBLASTN information from line
        tblastn_info = extract_TBLASTN_line(line)
        
        if tblastn_info:
            if tblastn_info[0] in tblastn_info_dict:
                #  Keep alignment with the highest identity
                #  This part can be modified to keep more alignments
                if tblastn_info_dict[tblastn_info[0]][0][-1] < tblastn_info[-1]:
                    tblastn_info_dict[tblastn_info[0]] = [tblastn_info[1:]]
            else:
                tblastn_info_dict[tblastn_info[0]] = [tblastn_info[1:]]
    return tblastn_info_dict

def extract_CDS_n_prot(
    reads_seq, 
    tblastn_info: list, 
    prot_seq: str
):
    """
    Extract CDS and protein sequences in the aligned region

    Parameters:
        reads_seq: reads sequence, Seq object (Bio.Seq.Seq) or str
        tblastn_info: list containing reads ID, protein start, protein end, ORF start, ORF end, direction and identity
        prot_seq: protein sequence in string
    
    Returns:
        orf_seq: extracted CDS region unified to + strand, str
        prot_part: extracted protein region, str
    """
    #  Load TBLASTN information
    prot_start = tblastn_info[0]
    prot_end = tblastn_info[1]
    orf_start = tblastn_info[2]
    orf_end = tblastn_info[3]
    direction = tblastn_info[4]

    if direction == 1:
        #  Positive strand
        orf_seq = str(reads_seq[orf_start:orf_end]).upper()
    else:
        #  Negative strand, extract the reverse complement sequence
        orf_seq = str(reads_seq[orf_start:orf_end].reverse_complement()).upper()
    
    prot_part = prot_seq[prot_start:prot_end]
    
    return orf_seq, prot_part

def rc(
    base: str
):
    """
    Convert given base to the reverse complement base

    Parameter:
        base: 1-bp DNA sequence, str
    
    Return:
        rc_base: reverse complement base, str
    """
    rc_dict = {
        'A': 'T',
        'T': 'A',
        'C': 'G',
        'G': 'C'
    }
    return rc_dict[base]

def determine_reads_mutation(
    reads_seq, 
    tblastn_infos: list, 
    prot_seq: str
):
    """
    Determine bases to be replaced

    Parameters:
        reads_seq: reads sequence, Seq object (Bio.Seq.Seq) or str
        tblastn_infos: list tblastn_info (list)
        prot_seq: protein sequence in string
    
    Returns:
        replace_dict: dictionary containing bases for replacement with positions as keys
    """
    replace_dict = {}
    
    for tblastn_info in tblastn_infos:
        #  Load TBLASTN information
        orf_start = tblastn_info[2]
        orf_end = tblastn_info[3]
        direction = tblastn_info[4]

        #  Extract CDS and protein regions
        orf_seq, prot_part = extract_CDS_n_prot(reads_seq, tblastn_info, prot_seq)
        
        codon_list = split_CDS(orf_seq)
        aa_list = [aa for aa in prot_part]
        
        #  Determine base replacement
        for codon_index in range(len(codon_list)):
            mut_dict = determine_codon_mutation(codon_list[codon_index], aa_list[codon_index])
            for mut_index in mut_dict:
                mut_pos = transf_reads_pos(orf_start, orf_end, direction, codon_index, mut_index)
                if direction == 1:
                    replace_dict[mut_pos] = mut_dict[mut_index]
                else:
                    replace_dict[mut_pos] = rc(mut_dict[mut_index])
    
    return replace_dict

def transf_reads_pos(
    orf_start: int,
    orf_end: int,
    direction: int,
    codon_index: int,
    mut_index: int
):
    """
    Calculate the actual position of base to be replaced

    Parameters:
        orf_start: ORF start index, int
        orf_end: ORF end index, int
        direction: 1 or -1 representing positive or negative strand, int
        codon_index: codon index in the extracted alignment region
        mut_index: position of base to be replaced in the codon

    Return:
        mut_pos: actual position of base in reads
    """
    if direction == 1:
        mut_pos = orf_start + 3 * codon_index + mut_index
    else:
        mut_pos = orf_end - 1 - (3 * codon_index + mut_index)
    
    return mut_pos

def fix_record(
    record, 
    replace_dict
):
    """
    Replace bases of reads sequence by replace_dict

    Parameters:
        record: SeqRecord object parsed from FASTQ file
        replace_dict: dictionary containing bases for replacement with positions as keys
    
    Return:
        record: SeqRecord object with fixed sequence
    """
    reads_seq_str = str(record.seq)
    for pos in replace_dict:
        reads_seq_str = reads_seq_str[:pos] + replace_dict[pos] + reads_seq_str[pos + 1:]
    record.seq = Seq(reads_seq_str)
    return record

def fix_reads(
    record, 
    tblastn_infos, 
    prot_seq
):
    """
    Replace bases of reads sequence by TBLASTN info and protein sequence

    Parameters:
        record: SeqRecord object parsed from FASTQ file
        tblastn_infos: list tblastn_info (list)
        prot_seq: protein sequence in string
    
    Return:
        fixed_record: SeqRecord object with fixed sequence
    """
    replace_dict = determine_reads_mutation(record.seq, tblastn_infos, prot_seq)
    fixed_record = fix_record(record, replace_dict)
    return fixed_record

def read_fq_dict(
    fq_path: str
):
    """
    Parse FASTQ file and store in dictionary

    Parameter:
        fq_path: file path of reads in FASTQ format
    
    Return:
        record_dict: dictionary containing SeqRecord from FASTQ file with reads IDs as keys
    """
    record_dict = {}
    for record in SeqIO.parse(fq_path, 'fastq'):
        record_dict[record.id] = record
    return record_dict

def write_fq(
    record_dict: dict, 
    out_path: str
):
    """
    Write FASTQ records into files

    Parameter:
        record_dict: dictionary containing SeqRecord from FASTQ file with reads IDs as keys
        out_path: file path of output FASTQ, str
    """
    records = []
    for record_id in record_dict:
        records.append(record_dict[record_id])
    SeqIO.write(records, out_path, 'fastq')

def fix_fq(
    fq_path: str, 
    blast_out_path: str, 
    prot_seq: str, 
    fix_fq_out_path: str
):
    """
    Process FASTQ file by TBLASTN result and protein sequence

    Parameter:
        fq_path: file path of reads in FASTQ format, str
        blast_out_path: file path of TBLASTN result generated by -outfmt 6, str
        prot_seq: protein sequence in string
        fix_fq_out_path: file path of output FASTQ, str
    """
    #  Load reads records
    record_dict = read_fq_dict(fq_path)
    #  Load TBLASTN results
    tblastn_info_dict = extract_TBLASTN(blast_out_path)

    #  Correct all reads
    for record_id in record_dict:
        if record_id in tblastn_info_dict:
            record_dict[record_id] = fix_reads(record_dict[record_id], tblastn_info_dict[record_id], prot_seq)
    
    #  Write into file
    write_fq(record_dict, fix_fq_out_path)



if __name__ == "__main__":
    #  Get file path of protein sequence in FASTA
    prot_path = sys.argv[1]
    prot_seq = str(SeqIO.read(prot_path, 'fasta').seq)
    #  Get file path of TBLASTN result
    blast_out_path = sys.argv[2]
    #  Get file path of reads in FASTQ format
    fq_path=sys.argv[3]
    #  Get file path of output FASTQ
    fix_fq_out_path=sys.argv[4]

    #  Run main program
    fix_fq(fq_path, blast_out_path, prot_seq, fix_fq_out_path)
